// Catalog schema: stable ID conventions, enum contracts and dependency-free
// validation functions for the generated GameData payload.
//
// This module is intentionally plain JavaScript (no external dependencies, no
// executable data) so the ETL and the tests share one single source of truth
// for the shape of `gamedata/generated/*.json`.
//
// Design references: docs/WOD游戏规则与系统设计.md sections 4, 5, 7.3, 8, 9.1,
// 14.1 and 22.

export const CATALOG_SCHEMA_VERSION = "catalog-schema-v1";

export const SKILL_PARSER_VERSION = "skill-page-v1";
export const ITEM_PARSER_VERSION = "item-page-v1";

/** Stable English attribute keys (design doc 6.2). */
export const ATTRIBUTE_KEYS = [
  "strength",
  "constitution",
  "intelligence",
  "dexterity",
  "charisma",
  "agility",
  "perception",
  "willpower",
];

/** Chinese attribute label -> stable English key. */
export const ATTRIBUTE_LABELS = {
  力量: "strength",
  体质: "constitution",
  智力: "intelligence",
  灵巧: "dexterity",
  魅力: "charisma",
  敏捷: "agility",
  感知: "perception",
  意志: "willpower",
};

/** base_type id -> stable English enum (design doc 4.2). */
export const BASE_TYPES = {
  1: "heal",
  2: "improve",
  3: "attack",
  4: "deteriorate",
  5: "summon",
  6: "defend",
  7: "initiative",
};

export const BASE_TYPE_IDS = {
  heal: 1,
  improve: 2,
  attack: 3,
  deteriorate: 4,
  summon: 5,
  defend: 6,
  initiative: 7,
};

export const TRAINING_CLASSES = ["basic", "additional", "special", "talent"];

export const TARGET_SIDES = ["ally", "enemy", "either"];
export const TARGET_MODES = ["self", "single", "samePositionAoE", "globalAoE"];

/**
 * Sentinel used when the page says a target count is "全部" (all). The target
 * mode already expresses the AoE semantics; this value means "no cap".
 */
export const UNLIMITED_TARGETS = Number.MAX_SAFE_INTEGER;

/** Modifier kinds produced by the parsers (design doc 14.1 plus extensions). */
export const MODIFIER_KINDS = [
  "flat",
  "percent",
  "scaledFlat",
  "scaledPercent",
  "randomFlat",
  "randomPercent",
  "unparsed",
];

export const MODIFIER_SCALES = ["skillLevel", "heroLevel"];
export const MODIFIER_ROLLS = ["damageRoll", "healingRoll"];

export const UNIQUENESS_VALUES = ["none", "hero", "team", "alliance"];

export const OWNER_PASSIVE_TARGET_KINDS = [
  "skill",
  "skillCategory",
  "attackType",
  "damageType",
  "attribute",
  "unknown",
];

/** Files written into gamedata/generated by build-catalog.mjs. */
export const CATALOG_FILES = [
  "manifest.json",
  "professions.json",
  "races.json",
  "skill-relations.json",
  "skills.json",
  "items.json",
  "enums.json",
  "quality-report.json",
];

/* ------------------------------------------------------------------ *
 * Small validation helpers
 * ------------------------------------------------------------------ */

const isString = (value) => typeof value === "string";
const isFiniteNumber = (value) => typeof value === "number" && Number.isFinite(value);
const isBoolean = (value) => typeof value === "boolean";
const isArray = (value) => Array.isArray(value);
const isPlainObject = (value) => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const isNullable = (test) => (value) => value === null || test(value);
const oneOf = (values) => (value) => values.includes(value);
const arrayOf = (test) => (value) => isArray(value) && value.every(test);
// Enum ids are numeric for most source tables and strings for equip_slot.
const isEnumId = (value) => typeof value === "string" || (typeof value === "number" && Number.isFinite(value));

function checkFields(value, fields, path, errors) {
  if (!isPlainObject(value)) {
    errors.push(`${path}: expected object, received ${describe(value)}`);
    return false;
  }
  let ok = true;
  for (const [key, test] of Object.entries(fields)) {
    if (!(key in value)) {
      errors.push(`${path}.${key}: missing`);
      ok = false;
      continue;
    }
    if (!test(value[key])) {
      errors.push(`${path}.${key}: invalid value ${describe(value[key])}`);
      ok = false;
    }
  }
  return ok;
}

function checkExtraKeys(value, allowed, path, errors) {
  if (!isPlainObject(value)) return;
  for (const key of Object.keys(value)) {
    if (!allowed.includes(key)) errors.push(`${path}.${key}: unexpected key`);
  }
}

function describe(value) {
  if (value === null) return "null";
  if (Array.isArray(value)) return `array(${value.length})`;
  if (typeof value === "string") return `string(${JSON.stringify(value.slice(0, 40))})`;
  return typeof value;
}

/** Canonical JSON (sorted keys, no whitespace) used for deterministic hashing. */
export function stableStringify(value) {
  return JSON.stringify(canonicalize(value));
}

function canonicalize(value) {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (isPlainObject(value)) {
    const out = {};
    for (const key of Object.keys(value).sort()) out[key] = canonicalize(value[key]);
    return out;
  }
  return value;
}

/**
 * Removes volatile fields (wall-clock timestamps) so a content hash stays
 * deterministic across runs. `generatedAt` and `parsedAt` are audit metadata,
 * never inputs of the content version.
 */
export function stripVolatileFields(value) {
  if (Array.isArray(value)) return value.map(stripVolatileFields);
  if (isPlainObject(value)) {
    const out = {};
    for (const [key, child] of Object.entries(value)) {
      if (key === "generatedAt" || key === "parsedAt") continue;
      out[key] = stripVolatileFields(child);
    }
    return out;
  }
  return value;
}

/* ------------------------------------------------------------------ *
 * Record validators. Each returns { ok, errors }.
 * ------------------------------------------------------------------ */

function validateWarnings(value, path, errors) {
  if (!arrayOf(isString)(value)) {
    errors.push(`${path}: expected string[]`);
    return;
  }
}

function validateMeta(meta, path, errors, sourceTable) {
  checkFields(
    meta,
    {
      sourceTable: isString,
      sourceName: isString,
      sourceHash: isString,
      parsedAt: isString,
      parserVersion: isString,
      warnings: isArray,
    },
    path,
    errors,
  );
  checkExtraKeys(
    meta,
    ["sourceTable", "sourceName", "sourceHash", "parsedAt", "parserVersion", "warnings"],
    path,
    errors,
  );
  if (isPlainObject(meta)) {
    if (meta.sourceTable !== sourceTable) {
      errors.push(`${path}.sourceTable: expected ${JSON.stringify(sourceTable)}`);
    }
    validateWarnings(meta.warnings, `${path}.warnings`, errors);
  }
}

export function validateModifier(modifier, path, errors) {
  if (modifier === null) return;
  if (!checkFields(modifier, { kind: oneOf(MODIFIER_KINDS) }, path, errors)) return;
  switch (modifier.kind) {
    case "flat":
    case "percent":
      checkFields(modifier, { value: isFiniteNumber }, path, errors);
      checkExtraKeys(modifier, ["kind", "value"], path, errors);
      break;
    case "scaledFlat":
    case "scaledPercent":
      checkFields(modifier, { ratio: isFiniteNumber, scale: oneOf(MODIFIER_SCALES) }, path, errors);
      checkExtraKeys(modifier, ["kind", "ratio", "scale"], path, errors);
      break;
    case "randomFlat":
      checkFields(modifier, { mean: isNullable(isFiniteNumber), rollPolicyId: isString }, path, errors);
      checkExtraKeys(modifier, ["kind", "mean", "rollPolicyId"], path, errors);
      break;
    case "randomPercent":
      checkFields(modifier, { value: isFiniteNumber, roll: oneOf(MODIFIER_ROLLS) }, path, errors);
      checkExtraKeys(modifier, ["kind", "value", "roll"], path, errors);
      break;
    case "unparsed":
      checkFields(modifier, { rawText: isString }, path, errors);
      checkExtraKeys(modifier, ["kind", "rawText"], path, errors);
      break;
    default:
      break;
  }
}

export function validateModifierEntry(entry, path, errors) {
  checkFields(entry, { rawText: isString, modifier: isNullable(isPlainObject), flags: isPlainObject }, path, errors);
  checkExtraKeys(entry, ["rawText", "modifier", "flags"], path, errors);
  if (isPlainObject(entry)) {
    validateModifier(entry.modifier, `${path}.modifier`, errors);
    checkFields(entry.flags, { a: isBoolean, z: isBoolean, r: isBoolean }, `${path}.flags`, errors);
    checkExtraKeys(entry.flags, ["a", "z", "r"], `${path}.flags`, errors);
  }
}

export function validateAttributePair(pair, path, errors) {
  if (pair === null) return;
  checkFields(
    pair,
    { primary: isNullable(oneOf(ATTRIBUTE_KEYS)), secondary: isNullable(oneOf(ATTRIBUTE_KEYS)) },
    path,
    errors,
  );
  checkExtraKeys(pair, ["primary", "secondary"], path, errors);
}

export function validateSkillRecord(record, path = "skill") {
  const errors = [];
  if (!checkFields(
    record,
    {
      id: isString,
      sourceId: isFiniteNumber,
      name: isString,
      baseType: isNullable(oneOf(Object.values(BASE_TYPES))),
      baseTypeId: isNullable(isFiniteNumber),
      attackTypeId: isNullable(isFiniteNumber),
      attackType: isNullable(isString),
      timing: isPlainObject,
      target: isNullable(isPlainObject),
      manaCost: isNullable(isPlainObject),
      itemRequirement: isNullable(isPlainObject),
      attributeFormula: isPlainObject,
      skillTypeNames: isArray,
      ownerPassives: isArray,
      skillLevelBonuses: isArray,
      targetEffects: isArray,
      parserVersion: isString,
      meta: isPlainObject,
    },
    path,
    errors,
  )) {
    return { ok: false, errors };
  }
  checkExtraKeys(
    record,
    [
      "id", "sourceId", "name", "baseType", "baseTypeId", "attackTypeId", "attackType",
      "timing", "target", "manaCost", "itemRequirement", "attributeFormula",
      "skillTypeNames", "ownerPassives", "skillLevelBonuses", "targetEffects", "parserVersion", "meta",
    ],
    path,
    errors,
  );
  if (isString(record.id) && isFiniteNumber(record.sourceId) && record.id !== `skill-${record.sourceId}`) {
    errors.push(`${path}.id: expected skill-${record.sourceId}`);
  }
  if (isFiniteNumber(record.baseTypeId) && isString(record.baseType)) {
    if (BASE_TYPES[record.baseTypeId] !== record.baseType) {
      errors.push(`${path}.baseType: ${record.baseType} does not match baseTypeId ${record.baseTypeId}`);
    }
  }
  if (record.baseTypeId === null && record.baseType !== null) {
    errors.push(`${path}.baseType: must be null when baseTypeId is null`);
  }
  checkFields(
    record.timing,
    {
      preRound: isBoolean,
      mainAction: isBoolean,
      initiative: isBoolean,
      reactiveDefense: isBoolean,
      passive: isBoolean,
    },
    `${path}.timing`,
    errors,
  );
  checkExtraKeys(
    record.timing,
    ["preRound", "mainAction", "initiative", "reactiveDefense", "passive"],
    `${path}.timing`,
    errors,
  );
  if (record.target !== null) {
    checkFields(
      record.target,
      {
        side: oneOf(TARGET_SIDES),
        mode: oneOf(TARGET_MODES),
        maxTargets: isFiniteNumber,
        allowSummons: isBoolean,
        rawText: isString,
      },
      `${path}.target`,
      errors,
    );
    checkExtraKeys(
      record.target,
      ["side", "mode", "maxTargets", "allowSummons", "rawText"],
      `${path}.target`,
      errors,
    );
  }
  if (record.manaCost !== null) {
    checkFields(
      record.manaCost,
      { standard: isNullable(isFiniteNumber), display: isNullable(isFiniteNumber), rawText: isString },
      `${path}.manaCost`,
      errors,
    );
    checkExtraKeys(record.manaCost, ["standard", "display", "rawText"], `${path}.manaCost`, errors);
  }
  if (record.itemRequirement !== null) {
    checkFields(
      record.itemRequirement,
      { rawText: isString, itemTypeName: isNullable(isString), categories: isArray },
      `${path}.itemRequirement`,
      errors,
    );
    checkExtraKeys(record.itemRequirement, ["rawText", "itemTypeName", "categories"], `${path}.itemRequirement`, errors);
    if (isArray(record.itemRequirement.categories)) {
      for (const [index, id] of record.itemRequirement.categories.entries()) {
        if (!isFiniteNumber(id)) errors.push(`${path}.itemRequirement.categories[${index}]: expected number`);
      }
    }
  }
  checkFields(
    record.attributeFormula,
    {
      attack: isNullable(isPlainObject),
      defense: isNullable(isPlainObject),
      damage: isNullable(isPlainObject),
    },
    `${path}.attributeFormula`,
    errors,
  );
  checkExtraKeys(record.attributeFormula, ["attack", "defense", "damage"], `${path}.attributeFormula`, errors);
  validateAttributePair(record.attributeFormula.attack, `${path}.attributeFormula.attack`, errors);
  validateAttributePair(record.attributeFormula.defense, `${path}.attributeFormula.defense`, errors);
  validateAttributePair(record.attributeFormula.damage, `${path}.attributeFormula.damage`, errors);
  if (!arrayOf(isString)(record.skillTypeNames)) errors.push(`${path}.skillTypeNames: expected string[]`);
  if (isArray(record.ownerPassives)) {
    for (const [index, row] of record.ownerPassives.entries()) {
      const rowPath = `${path}.ownerPassives[${index}]`;
      checkFields(
        row,
        {
          category: isString,
          columnHeaders: isArray,
          cells: isArray,
          targetKind: oneOf(OWNER_PASSIVE_TARGET_KINDS),
          targetName: isNullable(isString),
          targetSkillId: isNullable(isString),
          modifiers: isArray,
          rawText: isString,
          warnings: isArray,
        },
        rowPath,
        errors,
      );
      checkExtraKeys(
        row,
        ["category", "columnHeaders", "cells", "targetKind", "targetName", "targetSkillId", "modifiers", "rawText", "warnings"],
        rowPath,
        errors,
      );
      if (isArray(row.modifiers)) {
        for (const [mIndex, entry] of row.modifiers.entries()) {
          validateModifierEntry(entry, `${rowPath}.modifiers[${mIndex}]`, errors);
        }
      }
      validateWarnings(row.warnings, `${rowPath}.warnings`, errors);
    }
  }
  if (isArray(record.skillLevelBonuses)) {
    for (const [index, row] of record.skillLevelBonuses.entries()) {
      const rowPath = `${path}.skillLevelBonuses[${index}]`;
      checkFields(
        row,
        {
          targetSkillName: isString,
          targetSkillId: isNullable(isString),
          modifierRaw: isString,
          modifier: isNullable(isPlainObject),
          flags: isPlainObject,
          columns: isArray,
          warnings: isArray,
        },
        rowPath,
        errors,
      );
      checkExtraKeys(
        row,
        ["targetSkillName", "targetSkillId", "modifierRaw", "modifier", "flags", "columns", "warnings"],
        rowPath,
        errors,
      );
      validateModifier(row.modifier, `${rowPath}.modifier`, errors);
      validateWarnings(row.warnings, `${rowPath}.warnings`, errors);
    }
  }
  if (record.parserVersion !== SKILL_PARSER_VERSION) {
    errors.push(`${path}.parserVersion: expected ${SKILL_PARSER_VERSION}`);
  }
  validateMeta(record.meta, `${path}.meta`, errors, "skill_cache");
  return { ok: errors.length === 0, errors };
}

export function validateItemRecord(record, path = "item") {
  const errors = [];
  if (!checkFields(
    record,
    {
      id: isString,
      sourceId: isFiniteNumber,
      name: isString,
      slotId: isNullable(isString),
      slotName: isNullable(isString),
      // `item.slot` 的“不可装备”取值：非装备类物品，没有装备部位。
      nonEquippable: isBoolean,
      levelRange: isPlainObject,
      active: isBoolean,
      categories: isArray,
      modifiers: isNullable(isArray),
      triggeredEffects: isNullable(isArray),
      parseWarnings: isArray,
    },
    path,
    errors,
  )) {
    return { ok: false, errors };
  }
  checkExtraKeys(
    record,
    ["id", "sourceId", "name", "slotId", "slotName", "nonEquippable", "levelRange", "active", "categories", "modifiers", "triggeredEffects", "parseWarnings"],
    path,
    errors,
  );
  if (isString(record.id) && isFiniteNumber(record.sourceId) && record.id !== `item-${record.sourceId}`) {
    errors.push(`${path}.id: expected item-${record.sourceId}`);
  }
  checkFields(record.levelRange, { min: isFiniteNumber, max: isFiniteNumber }, `${path}.levelRange`, errors);
  checkExtraKeys(record.levelRange, ["min", "max"], `${path}.levelRange`, errors);
  if (isArray(record.categories)) {
    for (const [index, id] of record.categories.entries()) {
      if (!isFiniteNumber(id)) errors.push(`${path}.categories[${index}]: expected number`);
    }
  }
  if (record.modifiers !== null && isArray(record.modifiers)) {
    for (const [index, row] of record.modifiers.entries()) {
      const rowPath = `${path}.modifiers[${index}]`;
      checkFields(
        row,
        { category: isString, columnHeaders: isArray, cells: isArray, modifiers: isArray, rawText: isString, warnings: isArray },
        rowPath,
        errors,
      );
      checkExtraKeys(row, ["category", "columnHeaders", "cells", "modifiers", "rawText", "warnings"], rowPath, errors);
      if (isArray(row.modifiers)) {
        for (const [mIndex, entry] of row.modifiers.entries()) {
          validateModifierEntry(entry, `${rowPath}.modifiers[${mIndex}]`, errors);
        }
      }
    }
  }
  if (record.triggeredEffects !== null && isArray(record.triggeredEffects)) {
    for (const [index, row] of record.triggeredEffects.entries()) {
      const rowPath = `${path}.triggeredEffects[${index}]`;
      checkFields(
        row,
        { category: isString, columnHeaders: isArray, cells: isArray, modifiers: isArray, rawText: isString, warnings: isArray },
        rowPath,
        errors,
      );
      checkExtraKeys(row, ["category", "columnHeaders", "cells", "modifiers", "rawText", "warnings"], rowPath, errors);
      if (isArray(row.modifiers)) {
        for (const [mIndex, entry] of row.modifiers.entries()) {
          validateModifierEntry(entry, `${rowPath}.modifiers[${mIndex}]`, errors);
        }
      }
    }
  }
  validateWarnings(record.parseWarnings, `${path}.parseWarnings`, errors);
  return { ok: errors.length === 0, errors };
}

export function validateLearnableSkill(record, path = "learnableSkill") {
  const errors = [];
  if (!checkFields(
    record,
    {
      ownerKind: oneOf(["profession", "race"]),
      ownerId: isString,
      skillId: isString,
      trainingClass: oneOf(TRAINING_CLASSES),
      learnLevel: isFiniteNumber,
      advancedProfessionId: isNullable(isString),
      advancedProfessionName: isNullable(isString),
    },
    path,
    errors,
  )) {
    return { ok: false, errors };
  }
  checkExtraKeys(
    record,
    ["ownerKind", "ownerId", "skillId", "trainingClass", "learnLevel", "advancedProfessionId", "advancedProfessionName"],
    path,
    errors,
  );
  if (isNullable(isString)(record.advancedProfessionId) && isNullable(isString)(record.advancedProfessionName)) {
    if (record.advancedProfessionId !== null && record.advancedProfessionName === null) {
      errors.push(`${path}.advancedProfessionName: required when advancedProfessionId is set`);
    }
  }
  return { ok: errors.length === 0, errors };
}

export function validateProfessionRecord(record, path = "profession") {
  const errors = [];
  if (!checkFields(
    record,
    {
      id: isString,
      sourceId: isFiniteNumber,
      name: isString,
      known: isBoolean,
      warnings: isArray,
    },
    path,
    errors,
  )) {
    return { ok: false, errors };
  }
  checkExtraKeys(record, ["id", "sourceId", "name", "known", "warnings"], path, errors);
  validateWarnings(record.warnings, `${path}.warnings`, errors);
  return { ok: errors.length === 0, errors };
}

export function validateRaceRecord(record, path = "race") {
  const errors = [];
  if (!checkFields(
    record,
    { id: isString, sourceId: isFiniteNumber, name: isString, known: isBoolean, warnings: isArray },
    path,
    errors,
  )) {
    return { ok: false, errors };
  }
  checkExtraKeys(record, ["id", "sourceId", "name", "known", "warnings"], path, errors);
  validateWarnings(record.warnings, `${path}.warnings`, errors);
  return { ok: errors.length === 0, errors };
}

export function validateEnumsRecord(enums, path = "enums") {
  const errors = [];
  if (!checkFields(
    enums,
    {
      baseTypes: isArray,
      attackTypes: isArray,
      skillTypes: isArray,
      skillItemTypes: isArray,
      equipSlots: isArray,
      categories: isArray,
      usedTogetherCategories: isArray,
    },
    path,
    errors,
  )) {
    return { ok: false, errors };
  }
  for (const key of ["baseTypes", "attackTypes", "skillTypes", "skillItemTypes", "equipSlots", "categories", "usedTogetherCategories"]) {
    const list = enums[key];
    if (!isArray(list)) continue;
    for (const [index, entry] of list.entries()) {
      checkFields(entry, { id: isNullable(isEnumId), name: isString }, `${path}.${key}[${index}]`, errors);
    }
  }
  return { ok: errors.length === 0, errors };
}

export function validateManifest(manifest, path = "manifest") {
  const errors = [];
  if (!checkFields(
    manifest,
    {
      contentVersion: isString,
      generatedAt: isString,
      rulesetVersion: isString,
      schemaVersion: isString,
      counts: isPlainObject,
      parserVersions: isPlainObject,
      warnings: isArray,
      itemIndexNote: isString,
    },
    path,
    errors,
  )) {
    return { ok: false, errors };
  }
  checkExtraKeys(
    manifest,
    ["contentVersion", "generatedAt", "rulesetVersion", "schemaVersion", "counts", "parserVersions", "warnings", "itemIndexNote"],
    path,
    errors,
  );
  if (!/^[0-9a-f]{64}$/.test(manifest.contentVersion || "")) {
    errors.push(`${path}.contentVersion: expected a 64-char sha256 hex digest`);
  }
  for (const [key, value] of Object.entries(manifest.counts || {})) {
    if (!isFiniteNumber(value)) errors.push(`${path}.counts.${key}: expected number`);
  }
  for (const [key, value] of Object.entries(manifest.parserVersions || {})) {
    if (!isString(value)) errors.push(`${path}.parserVersions.${key}: expected string`);
  }
  validateWarnings(manifest.warnings, `${path}.warnings`, errors);
  return { ok: errors.length === 0, errors };
}

export function validateQualityReport(report, path = "qualityReport") {
  const errors = [];
  if (!checkFields(report, { generatedAt: isString, checks: isArray }, path, errors)) {
    return { ok: false, errors };
  }
  checkExtraKeys(report, ["generatedAt", "checks"], path, errors);
  if (isArray(report.checks)) {
    for (const [index, check] of report.checks.entries()) {
      const checkPath = `${path}.checks[${index}]`;
      checkFields(
        check,
        { check: isString, severity: oneOf(["error", "warning", "info"]), count: isFiniteNumber, samples: isArray },
        checkPath,
        errors,
      );
      checkExtraKeys(check, ["check", "severity", "count", "samples", "note"], checkPath, errors);
    }
  }
  return { ok: errors.length === 0, errors };
}

/**
 * Validates the whole generated catalog and the cross-file referential
 * integrity rules from design doc 22.
 */
export function validateCatalog(catalog) {
  const errors = [];
  const counts = {};
  const check = (result, label) => {
    if (!result.ok) errors.push(...result.errors.slice(0, 10).map((e) => `${label}: ${e}`));
    return result.ok;
  };

  check(validateManifest(catalog.manifest), "manifest");
  check(validateEnumsRecord(catalog.enums), "enums");
  check(validateQualityReport(catalog.qualityReport), "quality-report");

  const professionIds = new Set();
  for (const [index, record] of (catalog.professions || []).entries()) {
    check(validateProfessionRecord(record, `professions[${index}]`), "professions");
    professionIds.add(record.id);
  }
  const raceIds = new Set();
  for (const [index, record] of (catalog.races || []).entries()) {
    check(validateRaceRecord(record, `races[${index}]`), "races");
    raceIds.add(record.id);
  }
  counts.professions = professionIds.size;
  counts.races = raceIds.size;

  const skillIds = new Set();
  for (const [index, record] of (catalog.skills || []).entries()) {
    check(validateSkillRecord(record, `skills[${index}]`), "skills");
    if (skillIds.has(record.id)) errors.push(`skills[${index}].id: duplicate ${record.id}`);
    skillIds.add(record.id);
  }
  counts.skills = skillIds.size;

  const itemIds = new Set();
  for (const [index, record] of (catalog.items || []).entries()) {
    check(validateItemRecord(record, `items[${index}]`), "items");
    if (itemIds.has(record.id)) errors.push(`items[${index}].id: duplicate ${record.id}`);
    itemIds.add(record.id);
  }
  counts.items = itemIds.size;

  let relations = 0;
  for (const [index, record] of (catalog.skillRelations || []).entries()) {
    check(validateLearnableSkill(record, `skillRelations[${index}]`), "skill-relations");
    relations += 1;
    if (!skillIds.has(record.skillId)) {
      errors.push(`skillRelations[${index}].skillId: unknown skill ${record.skillId}`);
    }
    const ownerOk = record.ownerKind === "profession" ? professionIds.has(record.ownerId) : raceIds.has(record.ownerId);
    if (!ownerOk) errors.push(`skillRelations[${index}].ownerId: unknown ${record.ownerKind} ${record.ownerId}`);
  }
  counts.skillRelations = relations;

  return { ok: errors.length === 0, errors, counts };
}
